# Generated by Permit CLI
# Environment: 4158741e364a42beb17534b5c608102c
# Project: 33dfdf119d3b49789d7e0719f6b086ce
# Organization: 31c463a34dde4e419386fab48eb58706

terraform {
  required_providers {
    permitio = {
      source = "permitio/permit-io"
      version = "~> 0.0.12"
    }
  }
}

variable "PERMIT_API_KEY" {
  type        = string
  description = "The API key for the Permit.io API"
}

provider "permitio" {
  api_url = "https://api.permit.io"
  api_key = var.PERMIT_API_KEY
}

# Resources
resource "permitio_resource" "balance" {
  name        = "balance"
  description = ""
  key         = "balance"

  actions = {
    "transfer" = {
      name = "transfer"
    },
    "view" = {
      name = "view"
    }
  }
  attributes = {
  }
}
resource "permitio_resource" "account" {
  name        = "account"
  description = ""
  key         = "account"

  actions = {
    "read" = {
      name = "read"
    },
    "update" = {
      name = "update"
    },
    "create" = {
      name = "create"
    },
    "delete" = {
      name = "delete"
    }
  }
  attributes = {
  }
}
resource "permitio_resource" "change" {
  name        = "change"
  description = ""
  key         = "change"

  actions = {
    "make" = {
      name = "make"
    }
  }
  attributes = {
    "amount" = {
      name = "Amount"
      type = "number"
    },
    "currency" = {
      name = "Currency"
      type = "string"
    },
    "currency_country" = {
      name = "Currency Country"
      type = "string"
    }
  }
}

# User Attributes
resource "permitio_user_attribute" "user_location" {
  key         = "location"
  type        = "string"
  description = ""
}

# Roles
resource "permitio_role" "member" {
  key         = "member"
  name        = "member"
  permissions = ["account:read", "balance:view", "account:update"]

  depends_on  = [permitio_resource.account, permitio_resource.balance]
}

# Relations
resource "permitio_relation" "account_balance" {
  key              = "parent"
  name             = "parent"
  subject_resource = permitio_resource.account.key
  object_resource  = permitio_resource.balance.key
  depends_on = [
    permitio_resource.balance,
    permitio_resource.account,
  ]
}
resource "permitio_relation" "account_change" {
  key              = "parent"
  name             = "parent"
  subject_resource = permitio_resource.account.key
  object_resource  = permitio_resource.change.key
  depends_on = [
    permitio_resource.change,
    permitio_resource.account,
  ]
}

# Resource Sets
resource "permitio_resource_set" "No_approval_In_Region_Change" {
  name        = "No-approval In Region Change "
  key         = "No_approval_In_Region_Change"
  resource    = permitio_resource.change.key
  conditions  = jsonencode({
  "allOf": [
    {
      "allOf": [
        {
          "resource.currency_country": {
            "equals": {
              "ref": "user.location"
            }
          }
        },
        {
          "resource.amount": {
            "less-than": 1000.01
          }
        }
      ]
    }
  ]
})
  depends_on  = [
    permitio_resource.change
  ]
}
